"""Create DB

Revision ID: 0190f482f8c8
Revises: 959ed6f1a0f7
Create Date: 2024-11-16 12:33:26.653916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0190f482f8c8'
down_revision: Union[str, None] = '959ed6f1a0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('time_of_birth', sa.Time(), nullable=False),
    sa.Column('city_of_birth', sa.String(), nullable=False),
    sa.Column('zodiac_sign', sa.String(), nullable=False),
    sa.Column('house_1', sa.String(), nullable=False),
    sa.Column('house_2', sa.String(), nullable=False),
    sa.Column('house_6', sa.String(), nullable=False),
    sa.Column('house_7', sa.String(), nullable=False),
    sa.Column('house_9', sa.String(), nullable=False),
    sa.Column('house_10', sa.String(), nullable=False),
    sa.Column('house_11', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zodiac_statistic',
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('similarity_coef', sa.String(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('zodiac_statistic')
    op.drop_table('worker')
    # ### end Alembic commands ###
