"""Create user database

Revision ID: 959ed6f1a0f7
Revises: 01e7c41c2028
Create Date: 2024-11-16 07:36:39.309004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959ed6f1a0f7'
down_revision: Union[str, None] = '01e7c41c2028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company')
    # ### end Alembic commands ###
